### ISSUE TITLE
Issue: Joining an existing room won't display current Game Master

### ISSUE THREAD

**Issue by sasjakoning** [noyamirai/real-time-web-2223#13]
Joining an existing room won't display current Game Master. The red header remains empty.

![image](https://user-images.githubusercontent.com/13648845/233592740-211a1c1f-eb80-473a-8f53-2555b0d4cbeb.png)

**Comment by noyamirai** [comment]
I'll look into this

**Comment by noyamirai** [comment]
FIXED!!
