### ISSUE TITLE
Geen innerhtml gebruiken voor nicknames of berichten

### ISSUE THREAD

**Issue by Laurens256** [noyamirai/real-time-web-2223#19]
![image](https://user-images.githubusercontent.com/85798751/233620072-1591ec2c-d18e-4d6c-9c1d-5641c4fb704c.png)

![image](https://user-images.githubusercontent.com/85798751/233626088-26665e1d-16df-45b5-a950-e0d0593aac8e.png)

![image](https://user-images.githubusercontent.com/85798751/233626272-1285a7b2-0a5f-4c84-b7c2-d999dc2c57fa.png)

**Comment by noyamirai** [comment]
big brain test.... fixed it now for chat messages! on other parts im still using innerHtml because its data im sending back from the server
