### ISSUE TITLE
Implement multiple chat UI change

### ISSUE THREAD

**Issue by sasjakoning** [noyamirai/real-time-web-2223#5]
Currently, when typing multiple messages in the chat, the username keeps popping up above the message. It may be visually better to only display the username on top of the list of messages until another user starts chatting.

screenshot:
![image](https://user-images.githubusercontent.com/13648845/233589845-4fe76116-f526-43b6-8503-f23c759edc06.png)

Suggested UI:
![image](https://user-images.githubusercontent.com/13648845/233589989-b5d3b288-29ed-4093-b0c6-e00fb5f6cd1a.png)

**Comment by noyamirai** [comment]
I will fix this!!!

**Comment by noyamirai** [comment]
fixed :D
