### ISSUE TITLE
Issue: Creating a new lobby thinks other online users (in other rooms) are present as well

### ISSUE THREAD

**Issue by sasjakoning** [noyamirai/real-time-web-2223#6]
Due to this the empty lobby UI wont show up. 
![image](https://user-images.githubusercontent.com/13648845/233590281-2322c876-09ae-4113-80d8-ebe947ee90c0.png)

Possible solution:

When saving all online users to an object, section them in seperate room objects?

**Comment by noyamirai** [comment]
ahhh yes, I only save users in the object I sent back via 'ROOM_USERS'! Would be better to group them in separate room objects as you mentioned

**Comment by noyamirai** [comment]
should be fixed now!
