### ISSUE TITLE
Suggestion: Thumb wars

### ISSUE THREAD

**Issue by sasjakoning** [noyamirai/real-time-web-2223#7]
In addition to having a rock paper scissors game, you can add an alternative game mode involving thumb wars.

Two players are up against eachother to spam certain buttons as fast as possible to fill the bar. The person who spams buttons fastest wins the tumb war. This could be a cool alternative gamemode that adds a bit more interation compared to RPS.

**Comment by noyamirai** [comment]
Won't implement due to not enough time... if i have time left i will revisit this!
